# Generated by Django 6.0.3 on 2026-03-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, default='', max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('description', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('generation', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='family.familymember')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
